#!/usr/bin/env bash
# Open the auto-sync PR. Called from .github/workflows/sync-upstream.yml so
# we don't have to wrestle multi-line strings inside YAML pipe scalars.

set -euo pipefail

BRANCH="auto-sync/web-ui-${NEW_SHA}"
git config user.name "hermes-desktop-bot"
git config user.email "hermes-desktop-bot@users.noreply.github.com"
git checkout -b "$BRANCH"
git add -A

cat > /tmp/commit-msg.txt <<EOF
chore(deps): bump hermes-web-ui to ${NEW_SHA:0:12}

Bump submodule pointer + package.json version (${OLD_VER} → ${NEW_VER}).

Patches sanity-check: ${PATCHES_OK:-unknown}
EOF
git commit -F /tmp/commit-msg.txt

git push origin "$BRANCH"

cat > /tmp/pr-body.md <<EOF
Auto-generated by \`.github/workflows/sync-upstream.yml\`.

- hermes-web-ui: \`${OLD_SHA}\` → \`${NEW_SHA}\` (${COMMIT_COUNT} commits)
- package.json: \`${OLD_VER}\` → \`${NEW_VER}\`
- Patch sanity check: **${PATCHES_OK:-unknown}**

### Upstream commits

[Compare on GitHub](https://github.com/EKKOLearnAI/hermes-web-ui/compare/${OLD_SHA}...${NEW_SHA})

### Auto-merge policy

- 🟢 If patch sanity check passed AND CI is green → \`gh pr merge --auto --squash\` will merge once CI completes.
- 🟡 If patch sanity check failed → label \`needs-review\` is added; auto-merge disabled.
- 🔴 If CI fails → PR sits open, GitHub emails the owner.
EOF

PR_URL=$(gh pr create \
  --repo "$GITHUB_REPOSITORY" \
  --base main \
  --head "$BRANCH" \
  --title "chore(deps): bump hermes-web-ui ${COMMIT_COUNT} commits forward" \
  --body-file /tmp/pr-body.md \
  --label "auto-sync")
PR_NUM=$(echo "$PR_URL" | sed -E 's@.*/pull/([0-9]+).*@\1@')
echo "Opened PR #$PR_NUM ($PR_URL)"

if [ "${PATCHES_OK:-}" = "true" ]; then
  gh pr merge --auto --squash "$PR_NUM" --repo "$GITHUB_REPOSITORY"
  echo "✓ Auto-merge enabled (waits for CI)"
else
  gh pr edit "$PR_NUM" --repo "$GITHUB_REPOSITORY" --add-label "needs-review"
  echo "⚠ Patches lost anchors — labeled needs-review, auto-merge skipped"
fi
